language: node_js
node_js: stable
before_script:
- npm install -g gulp
script: gulp build
deploy:
  provider: heroku
  skip_cleanup: false
  api_key:
    secure: IULT+XSirZlcmjoOhB9kLZI0Bj0BDz+yehlHnKe1gQnOMoNvRq8a5HgwGxR4okLKP31JovBzzFzPDoM7hwE0pGoCuyPQJ8ijEm8I5GW6aGtcBj5D2R5MDjvMRXfiYqDn1P+iDwdnzHfZRwXUcYKYiN9QcKnamPwAao3Ueowc4N//XT/e1IwGkBttwXeHAe3uDNYHUaRzXeLAlaWWErwZuSWvVEqiotGIm2OLUfQhBTiPnFVfr7mXevXahKOfMkDxXRT/uMP3QRpmr6741OzS6mGxGiEKTX84NU/DR5AjlUclSIKcRVBwpHAlmm9fAf5aIkE7m/LMInZMYniMtYjEDC7tgnp3HZOzLAU3W4SUn4W1YxNi5zzhq2w6r6LqRhJnEWBZDtT/cMkvlD0WzH9wOJ7033oY/g/BKP5l5ZsX20/ca+oNXLC4dJJ3+ts/3q+ypTrWYbROzBP9jFsltaxfCOG/GSfQ4uU0x5IB1352NBE1qvq+4Ob2hXd17pl2rPbG+OKd7jhRhBojfwdiBdItr+gdWxPrLgk/mrUxOVZ9V2LDuGFzNfSJeC9UkiVLBCTl9DSMAc22uMkTfxLmlxKbD3ElPD7Lqi3uZwfo7N0SZHGxLrvSQCNOtd2AuOMw/0TL13c7mBBtPK6Xj0QTxyRVfVtNlieutVhlIycXYyHhiHU=
  app:
    master: evening-beyond-21116
  on:
    repo: ministryofjustice/oocp-cait
